/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 INIT CLOCKS
 ALL CLOCKS REQUIRED ARE INITIALIZED HERE
 */
void initClocks(void){
	RCC_AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC_APB2ENR |= RCC_APB2ENR_USART1EN;
}

/*
 CONFIG PINMODE
 CONFIGURE MDOES OF PIN
 */
void configPinMode(void){

	// CLEAR PA9 AND PA10
	GPIOA_MODER &= ~((3u << 18) | (3u << 20));

	// SET PA9 AND PA10 TO AF
	GPIOA_MODER |= ((2u << 18) | (2u << 20));

}

/*
 setAF
 CONFIGURE ALTERNATE FUNCTION
 */
void setAF(void){
	// RESET ALTERNATE FUNCTION
	// AF[1] IS THE ALTERNATE FUNCTION HIGH REGISTER
	// CLEAR PA9 AND PA10
	GPIOA_AFR1 &= ~((15u << 4) | (15u << 8));

	//SET ALTERNATE FUNCTION
	// SET PA9 AND PA10 AS AF
	GPIOA_AFR1 |= ((7u << 4) | (7u << 8));
}

/*
 configureUartPins
 CONFIGURES REQUIRED PINS TO BE USED AS UART PINS
 */

void configUart1Pins(void){

	// SET PIN MODE TO ALTERNATE FUNCTION
	configPinMode();

	// SET ALTERNATE FUNCTION TO BE UART1
	setAF();
}

/*
 configureUART1
 configures UART1 RELATED REGISTERS TO SET UP PERIPHERAL
 */
void configureUART1(void){
	USART1_CR1 &= ~( USART1_CR1_OVER8    // Clear OVER8 to use Oversampling by 16 (Bit 15)
	                | USART1_CR1_UE       // Clear UE to keep USART disabled for now (Bit 13)
	                | USART1_CR1_M        // Clear M for 1 Start bit, 8 Data bits (Bit 12)
	                | (0x1F << 4)        // Clear standard interrupts (PEIE, TXEIE, TCIE, RXNEIE, IDLEIE at Bits 4-8)
	                | USART1_CR1_TE       // Disable Transmitter (Bit 3)
	                | USART1_CR1_RE       // Disable Receiver (Bit 2)
	                );

	USART1_CR2 &= ~( USART1_CR2_LBDIE
	                | USART1_CR2_CLKEN
	                | USART1_CR2_STOP
	                | USART1_CR2_LINEN
	               );

	USART1_CR3 &= ~( USART1_CR3_EIE
					| (0x7F << 3)
					| USART1_CR3_IREN
			        );

	USART1_CR3 |= USART1_CR3_ONEBIT;

	// SET BAUD RATE TO 115200
	USART1_BRR = 139;

	//ENABLE UART
	USART1_CR1 &= ~( USART1_CR1_UE  //ENABLE UART1 (BIT 0)
					| USART1_CR1_RE  // ENABLE RECEIVER (BIT 2)
			        | USART1_CR1_TE   // ENABLE TRANSMITTER (BIT 3)
					);
}

/*
 *receiveUART
 THIS FUNCTION READS A BYTE OF DATA FROM RECEIVE DATA REGISTER, IF THERE IS DATA
 TO BE READ, AND RETURNS A BYTE OF DATA READ FROM RECEIVE DATA REGISTER
 */

uint8_t receiveUART(void){
	uint8_t rxData = 0;

	//IF THERE IS DATA IN RECEIVE DATA REGISTER
	// USART_ISR_RXNE EXPANDS TO (1 << 5)
	if (USART1_ISR & USART_ISR_RXNE){
		rxData = USART1_DR;
	}

	return rxData;
}

/*
 transmitUART(uint8_T data)
 This function sends a byte of data over UART
 */
void transmitUART(uint8_t data){
	//WAIT UNTILL TRANSMIT DATA REGISTER IS READY TO TAKE DATA
	//USART_ISR_TXE EXPANDS TO (1 << 7)
	while (!(USART1_ISR & USART_ISR_TXE));

	USART1_DR = data;
}

void transmitUART_String(const char *str) {
    while (*str) {
        transmitUART((uint8_t)*str);
        str++; // Move to the next character
    }
}

/*
 INIT UART
 THIS FUNCTION CONTAINS ALL CODE TO INITIALIZE UART
 */
void initUART(void){

	// INITIALIZE CLOCKS
	initClocks();

	//CONFIGURE PINS TO UART1
	configUart1Pins();

	// CONFIGURE UART1
	configureUART1();
}

void BLINK_LD2(void);

int main(void)
{
	// SET UP UART
	initUART();

	BLINK_LD2();

	while (1){
		if (receiveUART() > 0){
			transmitUART(85);
		}
	}
	//BLINK_LD2();


}
